{
 "title": "Session 20 - s20-metrics-app (Vansh Dobhal 10099)",
 "tags": [
  "session20",
  "flask"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Healthy targets (up)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{namespace=\"s20-app\", service=\"s20-metrics-app\"})"
    }
   ]
  },
  {
   "title": "Requests / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{namespace=\"s20-app\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx error ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{namespace=\"s20-app\",status=~\"5..\"}[2m])) / sum(rate(app_requests_total{namespace=\"s20-app\"}[2m]))"
    }
   ]
  },
  {
   "title": "Pod restarts (1h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"s20-app\"}[1h]))"
    }
   ]
  },
  {
   "title": "Request rate by endpoint & status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint, status) (rate(app_requests_total{namespace=\"s20-app\"}[1m]))",
     "legendFormat": "{{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "p95 latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(app_request_duration_seconds_bucket{namespace=\"s20-app\"}[2m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage (cores) per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"s20-app\", container=\"app\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory working set per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"s20-app\", container=\"app\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}