#!/usr/bin/env bash
# =============================================================================
# system_info.sh - Session 3 homework (Shell Scripting)
# Author : Vansh Dobhal | Roll No: 10099
#
# What it does:
#   1. Prints the current date, hostname and username
#   2. Prints disk usage (df -h) and the running processes (ps)
#   3. Stores all of that in variables and re-uses them
#   4. Asks the user for a directory name (read -p)
#   5. Creates that directory (mkdir) and an empty file inside it (touch)
#   6. Saves the running-process list into the file using '>' redirection
#
# Usage:
#   ./system_info.sh                 # interactive - asks for a directory name
#   ./system_info.sh <<< "mydir"     # non-interactive - name fed on stdin
# =============================================================================

set -euo pipefail          # stop on errors, unset variables and pipe failures

# ---------- 1. Collect system information into variables ----------
current_date=$(date '+%A, %d %B %Y %H:%M:%S %Z')   # command substitution $(...)
host_name=$(hostname)
user_name=$(whoami)
disk_usage=$(df -h /)                               # root filesystem only
process_count=$(ps -e --no-headers | wc -l)         # number of processes
divider="============================================================"

# ---------- 2. Print the information ----------
echo "$divider"
echo "               SYSTEM INFORMATION REPORT"
echo "$divider"
echo "Date      : $current_date"
echo "Hostname  : $host_name"
echo "Username  : $user_name"
echo
echo "---- Disk usage (df -h /) ----"
echo "$disk_usage"
echo
echo "---- Running processes of $user_name (ps) ----"
ps                                                  # processes of this terminal session
echo
echo "Total processes on the system: $process_count"
echo "$divider"

# ---------- 3. Take user input ----------
read -r -p "Enter a directory name to create: " dir_name

# default value if the user just pressed Enter
dir_name=${dir_name:-sysinfo_$(date +%Y%m%d_%H%M%S)}

# reject names containing a slash or starting with '-' (keeps it simple and safe)
if [[ "$dir_name" == */* || "$dir_name" == -* ]]; then
    echo "ERROR: '$dir_name' is not a valid simple directory name." >&2
    exit 1
fi
echo     # newline after the prompt (useful when input is piped)

# ---------- 4. Create directory and file ----------
if [[ -d "$dir_name" ]]; then
    echo "Directory '$dir_name' already exists - reusing it."
else
    mkdir -p "$dir_name"
    echo "Created directory : $dir_name"
fi

process_file="$dir_name/processes.txt"
touch "$process_file"
echo "Created file      : $process_file"

# ---------- 5. Store running processes in the file using '>' ----------
{
    echo "# Process snapshot taken on $current_date"
    echo "# Host: $host_name   User: $user_name   Total processes: $process_count"
    ps aux
} > "$process_file"            # '>' overwrites the file each run

echo "Saved $(wc -l < "$process_file") lines of 'ps aux' output to $process_file"
echo "Done. Report generated by $user_name on $host_name."
