apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pv-pod
  namespace: s13
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: dynamic-pvc
