apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-nodeport
  namespace: s11
  labels:
    app: web-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nodeport
  template:
    metadata:
      labels:
        app: web-nodeport
    spec:
      containers:
        - name: nginx-web
          image: nginx:1.25-alpine
          ports:
            - name: http
              containerPort: 80
          # Write the pod name into index.html so we can SEE which pod served each request
          command: ["sh", "-c", "echo \"Hello from pod $(hostname) (NodePort backend)\" > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]
          resources:
            requests: { cpu: "20m", memory: "32Mi" }
            limits:   { cpu: "100m", memory: "128Mi" }
