apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskboard.fullname" . }}-config
  labels: {{- include "taskboard.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  APP_VERSION: {{ .Values.backend.image.tag | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DB_HOST: {{ include "taskboard.dbHost" . | quote }}
  DB_PORT: "5432"
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
