#!/usr/bin/env bash
# Task 1 - every Helm command executed for real and captured with `snap`.
# Namespace: s15   Release: web1   Chart: ./webapp (generated by `helm create`)
D=~/devops-homework/session-15-helm/01-helm-commands
mkdir -p "$D"; cd "$D"
rm -rf webapp dist

snap 01-version-create --dir "$D" <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm version --short
helm create webapp
tree -a webapp
cat webapp/Chart.yaml | grep -v '^#' | grep -v '^$'
EOF

snap 02-lint-template --dir "$D" <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm lint webapp
helm lint webapp --strict
helm template web1 webapp -n s15 --show-only templates/deployment.yaml
helm template web1 webapp -n s15 | grep -E '^(kind|  name):'
EOF

snap 03-show-values --dir "$D" --max-lines 80 <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm show chart webapp
helm show values webapp | grep -v '^ *#' | grep -v '^$' | head -45
EOF

snap 04-dry-run --dir "$D" --max-lines 60 <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm install web1 webapp -n s15 --create-namespace --dry-run --set replicaCount=2 | head -12
helm install web1 webapp -n s15 --create-namespace --dry-run --set replicaCount=2 | grep -E 'replicas:|image:|kind:'
kubectl get all -n s15 2>&1 | head -3
EOF

snap 05-install --dir "$D" <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm install web1 webapp -n s15 --create-namespace
kubectl rollout status deployment/web1-webapp -n s15 --timeout=120s
kubectl get all -n s15
kubectl get secrets -n s15 -l owner=helm
EOF

snap 06-list-status --dir "$D" <<'EOF'
helm list -n s15
helm list -A
helm status web1 -n s15
helm status web1 -n s15 --show-resources | tail -n 20
EOF

snap 07-get-values-notes-manifest --dir "$D" --max-lines 90 <<'EOF'
helm get values web1 -n s15
helm get values web1 -n s15 --all | head -15
helm get notes web1 -n s15
helm get manifest web1 -n s15 | grep -E '^(# Source|kind|  name):'
helm get manifest web1 -n s15 | sed -n '/kind: Service$/,/^---/p'
EOF

snap 08-get-all --dir "$D" --max-lines 70 <<'EOF'
helm get all web1 -n s15 | head -40
helm get hooks web1 -n s15 | head -25
helm get metadata web1 -n s15
EOF

snap 09-upgrade --dir "$D" <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm upgrade web1 webapp -n s15 --set replicaCount=3
kubectl rollout status deployment/web1-webapp -n s15 --timeout=120s
kubectl get deploy web1-webapp -n s15
helm upgrade --install web1 webapp -n s15 --reuse-values --set service.type=NodePort
helm get values web1 -n s15
kubectl get svc,deploy -n s15
EOF

snap 10-history-rollback --dir "$D" <<'EOF'
helm history web1 -n s15
helm rollback web1 1 -n s15 --wait --timeout 120s
helm history web1 -n s15
kubectl get deploy,svc -n s15
helm get values web1 -n s15
EOF

snap 11-helm-test --dir "$D" <<'EOF'
helm test web1 -n s15 --logs
kubectl get pods -n s15
EOF

snap 12-repo-add-list-update --dir "$D" <<'EOF'
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo list
helm repo update
EOF

snap 13-search-repo-hub --dir "$D" --max-lines 80 <<'EOF'
helm search repo nginx | head -8
helm search repo prometheus-community/prometheus --versions | head -6
helm search repo bitnami/redis --version '>=20.0.0' | head -5
helm search hub wordpress --max-col-width 55 | head -8
helm show chart bitnami/nginx | grep -E '^(name|version|appVersion|description):'
helm show values bitnami/nginx | grep -E '^(replicaCount|  repository|  tag):' | head -6
EOF

snap 14-package-pull --dir "$D" --max-lines 70 <<'EOF'
cd ~/devops-homework/session-15-helm/01-helm-commands
helm package webapp -d dist
helm package webapp -d dist --version 0.2.0 --app-version 1.27.0
ls -l dist
tar -tzf dist/webapp-0.1.0.tgz
helm show chart dist/webapp-0.2.0.tgz | grep -E '^(name|version|appVersion):'
mkdir -p /tmp/s15-pull && helm pull prometheus-community/prometheus-node-exporter -d /tmp/s15-pull && ls -l /tmp/s15-pull
EOF

snap 15-uninstall-repo-remove --dir "$D" <<'EOF'
helm uninstall web1 -n s15 --wait
helm list -n s15 --all
kubectl get all,secrets -n s15
kubectl delete pod web1-webapp-test-connection -n s15 --wait
kubectl wait --for=delete pod -l app.kubernetes.io/instance=web1 -n s15 --timeout=90s
kubectl get all,secrets -n s15
helm repo remove bitnami
helm repo list
EOF
rm -rf /tmp/s15-pull
